name: NodeJS API Veracode Scan

on:
  push:
    branches:
      - dev
      - master
      
  pull_request:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          path: .
      - name: Publicando Artefato
        uses: actions/upload-artifact@v4
        with:
          name: pacoteVeracode
          path: veracode.zip

  Veracode_SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }} # Lembrar de criar as credenciais no Secrets
        run: |
          curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s – scan --update-advisor --pull-request --allow-dirty


  Veracode_SAST:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v4
        with:
          name: pacoteVeracode
      - uses: veracode/veracode-uploadandscan-action@master # Faz a analise da Veracode
        with:
          VID: ${{ secrets.VERACODE_API_ID }} 
          VKEY: ${{ secrets.VERACODE_API_KEY }}
          criticality: 'VeryHigh'
          AppName: ${{ github.repository }}
          appname: '$AppName'
          createsandbox: false
          filepath: 'veracode.zip'
          deleteIncompleteScan: true
          version: ${{ github.run_id }}

  Veracode_PipelineScan:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v4
        with:
          name: pacoteVeracode
      - name: Veracode Pipeline Scan
        env:
          VID: ${{ secrets.VERACODE_API_ID }} # Lembrar de criar as credenciais no Secrets
          VKEY: ${{ secrets.VERACODE_API_KEY }}
          caminhoPacote: './veracode.zip'
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY -f $caminhoPacote
